spring:
  application:
    name: webflux-app
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@webfluxcluster.tigdywe.mongodb.net/webfluxdb?retryWrites=true&w=majority&appName=webfluxCluster
      auto-index-creation: true